app:
  jwtSecret: "JWTTasker365Key"
  jwtExpirationInMs: 1209600000

spring:
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    show-sql: false
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

  datasource:
    url: jdbc:postgresql://localhost:5432/tasker365
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  sql:
    init:
      mode: always
